### ISSUE TITLE
Update OwnBackup

### ISSUE THREAD

**Issue by pbek** [owncloud/app-approval#10]
App name: OwnBackup
new/update: update
App store url: https://apps.owncloud.com/content/show.php/OwnBackup?content=170674
Development repo: https://github.com/pbek/ownbackup
Authors: @pbek

Comments:
- fixes for ownCloud 9.0

**Comment by oparoz** [comment]
Seems like the only real change is https://github.com/pbek/ownbackup/commit/7951c7cf54e4a2c7093e20d96ec09e1cb669fdfe

Seems fine to me. I've made a comment to improve it, but it's not blocking the approval process.

:+1: from me.

**Comment by pbek** [comment]
Thank you for your suggestion, @oparoz. I changed that now in the last commit.

**Comment by pbek** [comment]
Anything else to do for me to get the app approved?

**Comment by oparoz** [comment]
Patience until a store admin updates it... I think everybody is busy with fixing 9.0

**Comment by pbek** [comment]
Patience, I can do that. :) I'm doing that for three days for QOwnNotesAPI. ;)

**Comment by pbek** [comment]
Any news on the approval status?

**Comment by LukasReschke** [comment]
Approved. Sorry for the delay.

**Comment by jospoortvliet** [comment]
Congrats, @pbek ;-)

**Comment by pbek** [comment]
thanks :smile:
