### ISSUE TITLE
appvncsafeapp  , update

### ISSUE THREAD

**Issue by kapilnadiyapara** [owncloud/app-approval#12]
**App name** : appvncsafe
**new/update**: Update
**StoreURL**: https://apps.owncloud.com/content/show.php/appVNCsafe+for+Zimbra?content=155100
**Repo**: Attached zip file
**Authors**: VNC kapil.nadiyapara@vnc.biz, dhaval.dodiya@vnc.biz
**comments**: We have make this app compatible with owncloud 8 and owncloud 9. Owncloud App framework is nice to make App easily . Previiously this app name was appVNCsafe which is not working in new Owncloud versions so we make app name appvncsafe.
[appvncsafe.zip](https://github.com/owncloud/app-approval/files/320651/appvncsafe.zip)

**Comment by sualko** [comment]
Is there no repo for your project? Because nobody wants to review the whole code again and again and again...

**Comment by kapilnadiyapara** [comment]
@sualko : We have our own repo which is not public , and also that repo is use for our internal developer only. 

I have added the code zip here you can check it :)

Also we have update the app on the app store https://apps.owncloud.com/content/show.php/appVNCsafe+for+Zimbra?content=155100  which is updated successfully without any review :)

**Comment by sualko** [comment]
> I have added the code zip here you can check it :)

Yes, but on every update, even if it is only 1 line, I have to check the whole code, because I do not know which parts changed.

> which is updated successfully without any review :)

The app store is not reviewed, just the status in the owncloud internal app store.
