### ISSUE TITLE
appvncsafeapp , update

### ISSUE THREAD

**Issue by kapilnadiyapara** [owncloud/app-approval#14]
App name : appvncsafe
new/update: Update
StoreURL: https://apps.owncloud.com/content/show.php/appVNCsafe+for+Zimbra?content=155100
Repo: Attached zip file
Authors: VNC kapil.nadiyapara@vnc.biz, dhaval.dodiya@vnc.biz
comments: We have make this app compatible with  owncloud 9.1. 

NOTE: We are using our internal git repository for code maintain. Hence i am attaching the zip file for that app.

[appvncsafe.zip](https://github.com/owncloud/app-approval/files/401782/appvncsafe.zip)

**Comment by DeepDiver1975** [comment]
approved
