### ISSUE TITLE
QOwnNotesAPI 16.09.0

### ISSUE THREAD

**Issue by pbek** [owncloud/app-approval#15]
App name: QOwnNotesAPI
new/update: update
App store url: https://apps.owncloud.com/content/show.php/QOwnNotesAPI?content=173817
Development repo: https://github.com/pbek/qownnotesapi
Authors: @pbek

Comments:
- fixed a problem when the ownCloud or Nextcloud server didn't provide the path
  of a trashed note and thus no note was shown in the trash dialog of QOwnNotes
- increased `max-version` to `10.2`
- switched to rolling release version numbers

**Comment by DeepDiver1975** [comment]
> increased max-version to 10.2

???

**Comment by pbek** [comment]
Nextcloud compatibility. I've no idea how to address this without maintaining two releases that are the same but only differ in that configuration.

**Comment by DeepDiver1975** [comment]
nc 10 == oc 9.1
nc 11 == oc 9.2

so setting the max-version to 9.2 should be perfectly fine

**Comment by pbek** [comment]
@DeepDiver1975, thank you for letting me know! I just released the updated version. It's 9.2 now.

**Comment by pbek** [comment]
And I just released again for a description change.

**Comment by pbek** [comment]
I wonder if the nextcloud dependency I just added (because it seems the Nextcloud store seems to need it) will not cause problems... (oh, how much I love Forks)

**Comment by pbek** [comment]
@DeepDiver1975 are there any other obstacles?

**Comment by pbek** [comment]
anyone please? @danimo @PVince81 @DeepDiver1975 @dragotin

**Comment by DeepDiver1975** [comment]
approved

**Comment by pbek** [comment]
:+1:
