### ISSUE TITLE
user_sql, new

### ISSUE THREAD

**Issue by andyboeh** [owncloud/app-approval#16]
- **App name:** user_sql
- **new/update:** new
- **storeURL:** https://apps.owncloud.com/content/show.php/user_sql?content=155512
- **Repo:** https://code.rnb-consulting.at/diffusion/USQL/
- **authors:** @andyboeh
- **comments:**
  Code-Checker will complain about deprecated calls to OCP\JSON and OC_User. I do not know of alternatives that can be implemented easily. All deprecated calls are also used by user_ldap. The latest version on the app store contains more deprecated calls which have been fixed in the repo.

**Comment by andyboeh** [comment]
I just noticed that the SQL column and table settings are not escaped. Given the fact that only the admin has access to the settings interface, I did not yet update this part. I'm certain this needs to be fixed before it can be approved.

**Comment by andyboeh** [comment]
All configured SQL column and table settings are now verified (i.e. checked whether they are valid and exist) before the settings are saved. This should fix problems with SQL injection via the admin settings panel.

**Comment by DeepDiver1975** [comment]
approved - thanks a lot
