### ISSUE TITLE
New: Audio Player

### ISSUE THREAD

**Issue by Rello** [owncloud/app-approval#17]
`App name:` Audio Player
`new/update:` new
`StoreURL:` https://apps.owncloud.com/content/show.php/Audio+Player?content=174738
`Repo:` https://github.com/Rello/audioplayer
`authors:` @Rello @xraMsamohT 
`comments:` Audio player for OC with a quick and simple interface.
- [x] app:check-code green
- [x] signed
- [x] regularly maintained
- [x] >1 maintainer
- [x] Rating >60%
- [x] >3 months (originally forked form MP3 Player)

**Comment by JKawohl** [comment]
@PVince81 @DeepDiver1975 
Could somebody take a look please?
Thank you!

**Comment by Rello** [comment]
Wiki is also maintained

Thank you

**Comment by JKawohl** [comment]
@felixboehm  @DeepDiver1975 @PVince81 

Could you please check and approve?

**Comment by DeepDiver1975** [comment]
AudioPlayer has now the status approved in the appstore - THX
