### ISSUE TITLE
OwnBackup update

### ISSUE THREAD

**Issue by pbek** [owncloud/app-approval#19]
App name: OwnBackup
new/update: update
App store url: <https://apps.owncloud.com/content/show.php/OwnBackup?content=170674>
Development repo: <https://github.com/pbek/ownbackup>
Authors: @pbek

Comments:
- fixed an `internal server error` on ownCloud 9.1.2 (for [Issue #7](https://github.com/pbek/ownbackup/issues/7))
- added a notice to setup a cronjob to get periodic backups
- switched release versioning to a more *rolling release style*, so it doesn't get confused with semantic versioning

**Comment by DeepDiver1975** [comment]
done - thx

**Comment by pbek** [comment]
Thank you, @DeepDiver1975!
