### ISSUE TITLE
QOwnNotesAPI

### ISSUE THREAD

**Issue by pbek** [owncloud/app-approval#2]
App name: QOwnNotesAPI
new/update: is this the first review for approval
App store url: https://apps.owncloud.com/content/show.php/QOwnNotesAPI?content=173817
Development repo: https://github.com/pbek/qownnotesapi
Authors: @pbek

Comments:
- compliant by `occ app:check-code qownnotesapi`
- has automated testing and code coverage analysis
- is in public use for some month

**Comment by MorrisJobke** [comment]
cc @karlitschek @LukasReschke

**Comment by LukasReschke** [comment]
@pbek This looks like a CSRF vulnerability at https://github.com/pbek/qownnotesapi/blob/73513eaa8cf3c6b4b517afc76cda38ec9e9a525c/controller/noteapicontroller.php#L216

**Comment by pbek** [comment]
The functions are supposed to be called by https://apps.owncloud.com/content/show.php/QOwnNotes?content=168497, the desktop application QOwnNotes. So I cannot use CSRF-checking, or am I wrong?

**Comment by LukasReschke** [comment]
Ah. Sorry, forgot the CORS header. Should be good to go. Could use some more DI but otherwise looks fine. App is approved and should appear soon'ish as such.

**Comment by karlitschek** [comment]
great guys. this new process seems to work :-)

**Comment by pbek** [comment]
Yes, works like a charm! :) Thanks for the approve, @LukasReschke
