### ISSUE TITLE
New: onlyoffice

### ISSUE THREAD

**Issue by LinneyS** [owncloud/app-approval#22]
App name: onlyoffice
new/update: new
StoreURL: [https://apps.owncloud.com/content/show.php?content=174798](https://apps.owncloud.com/content/show.php?content=174798)
Repo: [https://github.com/ONLYOFFICE/onlyoffice-owncloud](https://github.com/ONLYOFFICE/onlyoffice-owncloud)
authors: Ascensio System SIA @LinneyS
comments: The application enables users to edit office documents from ownCloud using [ONLYOFFICE Document Server](https://github.com/ONLYOFFICE/DocumentServer).

**Comment by DeepDiver1975** [comment]
done - thx

**Comment by LinneyS** [comment]
Sorry, I forgot to specify in info.xml ocsid.
I need to create a new issue?

**Comment by DeepDiver1975** [comment]
> I need to create a new issue?

no - approved

**Comment by LinneyS** [comment]
Thank you
