### ISSUE TITLE
New: beame_insta_ssl

### ISSUE THREAD

**Issue by ilyash** [owncloud/app-approval#33]
* App name: beame_insta_ssl
* New/update: new
* StoreURL: n/a
* Repo: https://github.com/nextcloud/beame_insta_ssl
* Authors: Ilya Sher (is@beame.io)
* Comments: integrates [beame-insta-ssl](https://github.com/beameio/beame-insta-ssl/) tunnel. This eliminates the need for configuring inbound firewall and routing. beame-insta-ssl is somewhat similar to pagekite but more secure since private keys are generated on users' machines and Beame.io (which provides traffic routing service) can not open the traffic.

**Comment by ilyash** [comment]
Never mind. Looks like I followed outdated processes documentation.

**Comment by DeepDiver1975** [comment]
> Looks like I followed outdated processes documentation.

indeed - mind sharing where the outdated process is documented - we need to adjust this - THX

**Comment by ilyash** [comment]
I've told @jospoortvliet and he handled this: https://github.com/nextcloud/documentation/pull/540
