### ISSUE TITLE
New: Spreed.ME

### ISSUE THREAD

**Issue by leonklingele** [owncloud/app-approval#4]
- **App name**: Spreed.ME
- **new/update**: First time, new
- **StoreURL**: https://apps.owncloud.com/content/show.php/Spreed.ME?content=174436
- **Repo**: https://github.com/strukturag/owncloud-spreedme
- **authors**: @leonklingele
- **comments**:
  - Spreed.ME is a conferencing plugin which allows to meet with friends and family using rich audio-, video- and text chat right from your ownCloud installation right in your browser
  - Don't know if requirements are fulfilled, opening this review request anyway :smile_cat:

**Comment by MorrisJobke** [comment]
```
$ ./occ app:check-code spreedme
Version file isn't needed anymore and can be safely removed (apps/spreedme/appinfo/version)
App is compliant - awesome job!
```

Code checker wise looks good ;)

**Comment by LukasReschke** [comment]
Sorry for the delay on that one, Christmas Time :christmas_tree: :speak_no_evil: 

App is approved now and cool stuff, even installed it on my server. :rocket:

**Comment by jospoortvliet** [comment]
@LukasReschke so next CTO meeting we use Spreed.me? #fail that we didn't today...

**Comment by LukasReschke** [comment]
Sure thing. We can do that. With the new version you don't even need an account on my ownCloud :)
