### ISSUE TITLE
New JavaScript XMPP Chat (ojsxc)

### ISSUE THREAD

**Issue by sualko** [owncloud/app-approval#6]
- JavaScript XMPP Chat (ojsxc)
- new v3.0.0-beta2
- StoreURL: https://apps.owncloud.com/content/show.php?content=162257
- Repo Owncloud version: https://github.com/owncloud/jsxc.chat/
- Repo Core: https://github.com/jsxc/jsxc/
- authors: @sualko @LEDfan 
- comments: 
  - Please approve the latest [beta version of 3.0](https://github.com/owncloud/jsxc.chat/releases/tag/v3.0.0-beta2) so we can fix reported issues until the stable release
  - This owncloud app uses the standalone XMPP client [JSXC](https://www.jsxc.org).
  - This app should supersede ownclouds [chat](https://github.com/owncloud/chat) in consultation with @jancborchardt 
  - This app was original designed as a normal XMPP client and required therefore a working XMPP server. Starting with this release @LEDfan implemented an experimental internal server backend (not all functions available)
  - Main features: One-to-one (end-to-end encrypted) chat, multi-user chat, video calls, file transfer
  - JSXC is maintained in cooperation with the [Distributed Systems Laboratory](http://www.disy.uni-konstanz.de/) (@MarcelWaldvogel, @DanScharon) and the Collaboration project of the Communications, Information, Media Centre at the [University of Konstanz](http://www.uni-konstanz.de/). This project is supported in part by the [Ministry of Science, Research, and Arts](http://mwk.baden-wuerttemberg.de/de/) of the German state of Baden-Württemberg and University of Konstanz.

![Screenshot](https://www.jsxc.org/assets/screenshot-owncloud-latest.png)

**Comment by karlitschek** [comment]
nice. @LukasReschke What do you think?

**Comment by LukasReschke** [comment]
Please define the dependencies such as: 

```
    <dependencies>
        <owncloud min-version="8.2" max-version="8.2" />
    </dependencies>
```

And remove the `require` in your appinfo.xml, this will prevent bugs in case users are updating to a newer ownCloud version and this app may out of all sudden be incompatible. Make sure to just specify what you really know to support.

<hr/>

Besides this no complaints from my side :+1:

**Comment by jancborchardt** [comment]
Very nice! The design has really come a long way! :)

Only one thing: The font-weight of the letter in the avatar placeholder should _not_ be bold, like in core.
(Also it seems like Open Sans is not correctly loaded for your ownCloud, as everything is in a default system font.)

**Comment by sualko** [comment]
> Please define the dependencies such as

Already  [done](https://github.com/owncloud/jsxc.chat/blob/master/appinfo/info.xml) in 3.0-beta.

> And remove the require in your appinfo.xml

<code>requiremin</code> is included, because it is defined in the [developer manual](https://doc.owncloud.org/server/8.0/developer_manual/app/info.html) of oc 8.0. I guess it should be also no problem for further oc versions.

> Also it seems like Open Sans is not correctly loaded for your ownCloud

Screenshot was taken on an apple mac, not sure if it is shipped with open sans by default.

Anything else, or could 3.0-stable be approved?

**Comment by jancborchardt** [comment]
@sualko Open Sans is shipped by ownCloud. Any JS console errors?

And did you fix the placeholder boldness? I also assume you use the correct placeholder.js function from core?

**Comment by sualko** [comment]
@jancborchardt Open Sans is correctly loaded and used for all oc elements. The placeholder are not bold, they are in Arial. Will change that in the next days.

>  I also assume you use the correct placeholder.js function from core?

I say only standalone application ;-).

**Comment by jancborchardt** [comment]
Yeah, better get rid of any Arial. ;)

**Comment by sualko** [comment]
I know everyone is busy with ownCloud, but we releases 3.0 stable in the meanwhile. Just as a side note.

**Comment by jancborchardt** [comment]
I only have some more things regarding design review:
- [ ] can you make the emoji popover background white instead of dark? So it’s like the file actions menu
- [ ] the message window header using ownCloud dark blue feels off. That color is only used sparingly and seems misplaced here. A bright one would be better, similar to the one when it’s collapsed (»Ilias D« in your screenshot)
- [ ] the background of the friends list as well as the message window should really be white, just like the left navigation bar and files sidebar are as well. Otherwise it doesn’t fit with the new light design of ownCloud which we have since 8.2

**Comment by sualko** [comment]
I think we discussed most of your points and this should not prevent the approval. Am I right?

**Comment by LukasReschke** [comment]
Let's approve. This should not prevent an approval.

**Comment by jancborchardt** [comment]
@sualko okidoke. Where do I ideally open these issues now? :)

**Comment by jospoortvliet** [comment]
I guess here? https://github.com/jsxc/jsxc/issues
