### ISSUE TITLE
New: Registration

### ISSUE THREAD

**Issue by pellaeon** [owncloud/app-approval#7]
- Registration
- new/update: first time, new
- StoreURL: https://apps.owncloud.com/content/show.php?content=170608
- Repo: https://github.com/pellaeon/registration
- authors: @pellaeon
- comments:
  - code-checker will complain on the line https://github.com/pellaeon/registration/blob/master/appinfo/app.php#L17 , but `\OC_App::registerLogIn()` is vital to this app, to add a registration button on the login page, and currently no public interface is able to do that.

**Comment by LukasReschke** [comment]
From https://github.com/pellaeon/registration/blob/00833216aecbcf90a107da0a2c6ccfbdacb96c3f/appinfo/info.xml:

```
    <dependencies>
        <owncloud min-version="8.1" max-version="10.0"/>
    </dependencies>
```

Please define the real max version which is likely 8.2 here.

<hr/>

Besides this, no other immediate complaints from me :+1:

**Comment by sualko** [comment]
Just from reading, it looks good. Found only an probable unused [file](https://github.com/pellaeon/registration/blob/master/js/script.js). 

[domains.php#L6-L12](https://github.com/pellaeon/registration/blob/master/templates/domains.php#L6-L12) would be maybe more readable if you would write it as:

```
<?php foreach ($_['domains'] as $domain ): ?>
    <p class='hint'>
        <?php p($domain); ?>
    </p>
<?php endforeach; ?>
```

But this a personal preferences, so no showstopper :dancer:.

Is the <code>str_replace</code> required in [email.validate_plaintext.php#L3](https://github.com/pellaeon/registration/blob/master/templates/email.validate_plaintext.php#L3)?

#6

**Comment by pellaeon** [comment]
Just updated Registration to v0.1.2, fixed all issues above.

@sualko your app is quite big ;-) is there any part that particularly needs testing and reviewing?

**Comment by sualko** [comment]
>  is there any part that particularly needs testing and reviewing?

I would say it is enough if you go through the oc code and look for any suspicious parts. Or install it and click around and look for any usability issues.

**Comment by jospoortvliet** [comment]
Should be approved now.
