### ISSUE TITLE
Update QOwnNotesAPI

### ISSUE THREAD

**Issue by pbek** [owncloud/app-approval#9]
I got QOwnNotesAPI approved last year in #2 but it seems now it is experimental again.
Is there any reason for it?
The app is still compliant by `occ app:check-code qownnotesapi`...

**Comment by LukasReschke** [comment]
Yes… Each update requires resetting the privilege from what I understand.

cc @karlitschek Do we want to keep the old level for updates?

**Comment by oparoz** [comment]
I think it's risky because updates can vary greatly.

**Comment by pbek** [comment]
But you loose all the user trust with every update and every app would have to reapply after an update. I don't think that's a great idea neither.

my changes were: https://github.com/pbek/qownnotesapi/commit/027c97918a18246ca26b430bceafa6575b5cf501

**Comment by oparoz** [comment]
> But you loose all the user trust with every update 

Temporarily, yes

> every app would have to reapply after an update.

I think so far, people at ownCloud have done a good job at quickly going through changes, but as more apps become approved and as more complex updates are submitted, then there will eventually be some delays.

Don't forget that once you become a trusted developer you're given the right to manage that approval status, if I'm not mistaken.

**Comment by oparoz** [comment]
@pbek, check out this issue: https://github.com/owncloud/appstore-issues/issues/24

**Comment by pbek** [comment]
> Don't forget that once you become a trusted developer you're given the right to manage that approval status, if I'm not mistaken.

Where can I manage that status?

> check out this issue: owncloud/appstore-issues#24

thank your for the link, what is it I should look out for?

**Comment by oparoz** [comment]
> Where can I manage that status?

You see it once you can manage it

> what is it I should look out for?

https://github.com/owncloud/appstore-issues/issues/24#issuecomment-116366273

**Comment by pbek** [comment]
Thank you. So how do I know if I am a trusted developer? My username is `pbe78`.

**Comment by pbek** [comment]
But first: Can I please get QOwnNotesAPI approved again?

**Comment by pbek** [comment]
Any news, @LukasReschke, @oparoz ?

**Comment by pbek** [comment]
I just added a `max-version="9.0"` setting in the `info.xml` and am still hoping for reapproval. :smile_cat:

**Comment by pbek** [comment]
App name: QOwnNotesAPI
new/update: update
App store url: https://apps.owncloud.com/content/show.php/QOwnNotesAPI?content=173817
Development repo: https://github.com/pbek/qownnotesapi
Authors: @pbek

Comments:
- minor new features

**Comment by oparoz** [comment]
Changes in https://github.com/pbek/qownnotesapi/commit/027c97918a18246ca26b430bceafa6575b5cf501 look fine to me.

:+1:

**Comment by pbek** [comment]
Thank you, @oparoz!

**Comment by pbek** [comment]
Anything else to do for me to get the app approved?

**Comment by pbek** [comment]
Any news on the approval status?

**Comment by pbek** [comment]
I get user complaints about the experimental status of QOwnNotesAPI. :disappointed:

**Comment by LukasReschke** [comment]
Approved. Sorry for the delay.
